- app/views/catalog/_viewer.html.erb
- spec/features/item_view_spec.rb
This reverts commit 6207ff2e287ffe3fe4dd7edc9efb940b0cc374f4, reversing
changes made to ce5fcd273d1eadc8892e34d4d9650c69bed31005.
> Revert "Merge pull request #386 from cul-it/DIGCOLL-671"

- Gemfile
- Gemfile.lock
- app/helpers/blacklight_helper.rb
- app/views/catalog/_index_header_default.html.erb
- app/views/catalog/_show_header_default.html.erb
* translated titles for JCM. added xray for dev
* remove helper not being used
> Digcoll 1052 (#620)

- app/controllers/catalog_controller.rb
- app/helpers/blacklight_helper.rb
- app/views/catalog/_issue_list.html.erb
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_viewer.html.erb
- app/views/pages/collections/chla/_header.html.erb
- app/views/pages/collections/chla/index.html.erb
* chla viewer
* chla mods
* chla thumbs
> Chla (#660)

- app/controllers/catalog_controller.rb
* iwo fields
* blashcka and iwo fields
> Digcoll 1144 (#674)

- app/controllers/catalog_controller.rb
- app/helpers/blacklight_helper.rb
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_viewer.html.erb
- app/views/pages/collections/wordsworth/index.html.erb
* publication field
* wordsworth collection
> Digcoll 834 (#694)

- app/views/catalog/_viewer.html.erb
* add rudin case to viewer
* s3 path
> Rudin readers (#781)

- app/controllers/catalog_controller.rb
Getting dev caught up with master and commenting out unused helper reference
> Fixhearthidentifiers

- app/controllers/application_controller.rb
- app/controllers/catalog_controller.rb
- app/views/catalog/_show_default.html.erb
- app/views/catalog/_viewer.html.erb
- app/views/catalog/show.html.erb
Improve permissions for viewing objects in prod, stg, dev, bento and shorten the filter query for 
DIGCOLL-1619
> Release/digcoll 1545 2 - shorten filter query

- app/controllers/application_controller.rb
Wordsworth id prefix
Include all gamelan
Special test for adler
> Special treatment for gamelan and adler collectons in the filter query

- app/helpers/application_helper.rb
- app/helpers/blacklight_helper.rb
- app/views/catalog/show.html.erb
Now use the regular field query to see if an asset should be visible or 'Item restricted'
> Digcoll 1659 - assets visible in production when they should not be

- app/controllers/application_controller.rb
- app/helpers/blacklight_helper.rb
- app/views/catalog/_facet_pagination.html.erb
- app/views/catalog/_multi_images.html.erb
Facet modal previous/next buttons stay in modal.
> Dev - DIGCOLL-1670

- app/controllers/application_controller.rb
- features/content/content.feature
- features/step_definitions/general_steps.rb
- features/step_definitions/searchresults.rb
- features/step_definitions/web_steps.rb
New tests for Articles in facets, and for individual assets from collections that should not show in production.
> Digcoll 1682 - tests for Do not display Articles in production

- app/controllers/application_controller.rb
- features/content/content.feature
- features/step_definitions/general_steps.rb
- features/step_definitions/searchresults.rb
- features/step_definitions/web_steps.rb
Article facet and individual assets that should not show in production.
> Dev - tests for Article visibility in production

- app/helpers/blacklight_helper.rb
- features/fields/image.feature
One Forum collection can have both compound objects and multi-image objects
> Digcoll 1677 - detection of multi-image assets

- app/helpers/blacklight_helper.rb
- features/fields/image.feature
- run-all-tests.sh
One Forum collection can have both compound objects and multi-image objects
> Digcoll 1677 a - One Forum collection can have both compound objects and multi-image objects

- app/controllers/application_controller.rb
- app/helpers/blacklight_helper.rb
- features/content/content.feature
- features/fields/image.feature
- features/step_definitions/general_steps.rb
- features/step_definitions/searchresults.rb
- features/step_definitions/web_steps.rb
- run-all-tests.sh
DIGCOLL-1677
One Forum collection can have both compound objects and multi-image objects
> Dev - DIGCOLL-1677

- app/helpers/blacklight_helper.rb
- app/views/catalog/_viewer.html.erb
- features/collections/counts.feature
- features/content/content.feature
- features/fields/image.feature
- features/fields/regular.feature
- features/step_definitions/asset_fields.rb
- features/step_definitions/general_steps.rb
- run-all-tests.sh
Look for iiif images using two AWS S2 paths.
> Digcoll 1680 - either path for iiif static images

- features/fields/image.feature
Tests used to fail timing out on piwick.js
> Enable @javascript tests to check piwick.js on awsjenkins

- Gemfile
- Gemfile.lock
- features/collections/counts.feature
- features/fields/image.feature
add phantomjs to Gemfile and uncomment @javascript tests
> Digcoll 1683 f

- features/collections/counts.feature
Collection count test failing since someone is adding items to the collection.
> Digcoll 1684 - comment out test for Adler count

- features/collections/counts.feature
Update pjmode and comment out chla (active)
> Digcoll 1684 b - collection counts

- features/collections/counts.feature
* Adler collection count is in flux - comment out temporarily
* pjmode collection has settled down
* fix pjmode collection count
* comment out chla count - actively being added to
> Digcoll 1684 b - collection counts (#1220)

- app/helpers/blacklight_helper.rb
- features/content/content.feature
- features/step_definitions/searchresults.rb
- features/step_definitions/web_steps.rb
> Digcoll 1686 b  - multi-view excluded from index yet visible in production

- app/helpers/blacklight_helper.rb
- features/content/content.feature
- features/step_definitions/searchresults.rb
- features/step_definitions/web_steps.rb
> Digcoll 1686 c multi-view excluded from index yet visible in production 

- app/helpers/blacklight_helper.rb
- features/collections/counts.feature
- features/content/content.feature
- features/step_definitions/searchresults.rb
- features/step_definitions/web_steps.rb
Un-suppress multi-view items 2 TO *
> DIGCOLL-1686 - Make multi-view images visible in production

- app/views/catalog/_multi_images.html.erb
- features/collections/counts.feature
- features/fields/dlxs.feature
- features/fields/image.feature
Testing after AWS upgrade failed on these unrelated issues.
> Update collection counts - fix problems in tests

- app/helpers/blacklight_helper.rb
- app/views/catalog/_multi_images.html.erb
- features/collections/counts.feature
- features/content/content.feature
- features/fields/dlxs.feature
- features/fields/image.feature
- features/step_definitions/searchresults.rb
- features/step_definitions/web_steps.rb
> Update collection counts

- app/controllers/catalog_controller.rb
Add metadata to ezra collection
> add people_tesim

- app/controllers/catalog_controller.rb
add geography_tesim to catalog_controller.rb
> add geography_tesim

- features/collections/counts.feature
- features/content/content.feature
- features/fields/dlxs.feature
- features/fields/image.feature
Attempt to fix outstanding cucumber tests. Collection counts, newly published items, multi-image items now compound objects, etc.
> Digcoll 1585 - update counts and other cucumber tests

- app/helpers/blacklight_helper.rb
- app/views/catalog/_multi_images.html.erb
Sometimes document returned without id prefix???
> DIGCOLL-1836 - prevent multi-image displays from including the current asset

- features/collections/counts.feature
- features/fields/dlxs.feature
Fix up the failing tests - collection counts and one dlxs content change
> DIGCOLL-1836 - fix test counts and dlxs witchcraft extent test

- CHANGELOG.md
> trigger change for MAP version

- CHANGELOG.md
https://awsjenkins.library.cornell.edu/view/Portal/job/DigitalCollectionsPortal/
has the solr core listed in it. It's not just a change in .env!
> Digcoll 1542 b - also change solr core in Jenkins job

- CHANGELOG.md
The name of the core is TWO places in https://awsjenkins.library.cornell.edu/view/Portal/job/DigitalCollectionsPortal/
> another triggering change - fix another reference to core

- features/fields/MAP.feature
Many AppSignal errors from missing facets
> DIGCOLL-1877 - Disable facet listing page

- app/views/catalog/_viewer_pdf.html.erb
> DIGCOLL-1903 - fix path

- features/collections/counts.feature
- features/collections/metadata.feature
- features/step_definitions/collections.rb
- features/step_definitions/searchresults.rb
Change tests for collection count to allow slop, adjust for ezra collection name and new links to collection websites
> Digcoll 1911 - fix tests

- app/controllers/application_controller.rb
- app/views/catalog/_show_default.html.erb
- features/collections/counts.feature
- features/content/content.feature
- features/step_definitions/searchresults.rb
DIGCOLL-1665 - no suppressed records in digital-stg
DIGCOLL-1900 - change display of multi-image records in search results
> Digcoll 1900 b - kmoddl multi-image display and DIGCOLL-1665

- spec/features/search_spec.rb
remove the expections of Welcome! text in RSpec tests
> Digcoll 1999 tests
